-- Migration: 0002_seed_instruments
-- Description: Seed instruments table with PROFILE_CATALOG data

INSERT INTO instruments (symbol, name, exchange, sector, asset_class, market_cap, reference_price, eps, coin_gecko_id) VALUES
-- Equities
('AAPL', 'Apple Inc.', 'NASDAQ', 'Technology', 'equity', 3400000000000, 242, 6.5, NULL),
('MSFT', 'Microsoft Corp.', 'NASDAQ', 'Technology', 'equity', 3200000000000, 430, 11.8, NULL),
('NVDA', 'NVIDIA Corp.', 'NASDAQ', 'Technology', 'equity', 2700000000000, 875, 2.9, NULL),
('TSLA', 'Tesla Inc.', 'NASDAQ', 'Consumer Cyclical', 'equity', 800000000000, 250, 3.1, NULL),
('GOOGL', 'Alphabet Inc.', 'NASDAQ', 'Communication Services', 'equity', 2200000000000, 180, 7.2, NULL),
('AMZN', 'Amazon.com Inc.', 'NASDAQ', 'Consumer Cyclical', 'equity', 2100000000000, 200, 6.3, NULL),
('META', 'Meta Platforms', 'NASDAQ', 'Communication Services', 'equity', 1400000000000, 560, 18.7, NULL),
('BRK-B', 'Berkshire Hathaway', 'NYSE', 'Financial Services', 'equity', 1000000000000, 455, 35.5, NULL),
('JPM', 'JPMorgan Chase', 'NYSE', 'Financial Services', 'equity', 650000000000, 235, 17.6, NULL),
('BAC', 'Bank of America', 'NYSE', 'Financial Services', 'equity', 350000000000, 44, 3.3, NULL),
('GS', 'Goldman Sachs', 'NYSE', 'Financial Services', 'equity', 180000000000, 520, 37.2, NULL),
('MS', 'Morgan Stanley', 'NYSE', 'Financial Services', 'equity', 230000000000, 124, 6.7, NULL),
('V', 'Visa Inc.', 'NYSE', 'Financial Services', 'equity', 600000000000, 300, 10.2, NULL),
('MA', 'Mastercard Inc.', 'NYSE', 'Financial Services', 'equity', 500000000000, 500, 14.1, NULL),
('PYPL', 'PayPal Holdings', 'NASDAQ', 'Financial Services', 'equity', 80000000000, 74, 4.2, NULL),
('XOM', 'Exxon Mobil', 'NYSE', 'Energy', 'equity', 500000000000, 119, 8.6, NULL),
('CVX', 'Chevron Corp.', 'NYSE', 'Energy', 'equity', 290000000000, 160, 10.4, NULL),
('COP', 'ConocoPhillips', 'NYSE', 'Energy', 'equity', 140000000000, 112, 8.7, NULL),
('SLB', 'Schlumberger', 'NYSE', 'Energy', 'equity', 65000000000, 50, 3.4, NULL),
('UNH', 'UnitedHealth Group', 'NYSE', 'Healthcare', 'equity', 450000000000, 560, 27.5, NULL),
('JNJ', 'Johnson & Johnson', 'NYSE', 'Healthcare', 'equity', 390000000000, 155, 10.1, NULL),
('PFE', 'Pfizer Inc.', 'NYSE', 'Healthcare', 'equity', 180000000000, 28, 2.6, NULL),
('KO', 'Coca-Cola Co.', 'NYSE', 'Consumer Defensive', 'equity', 280000000000, 69, 2.8, NULL),
('PEP', 'PepsiCo Inc.', 'NASDAQ', 'Consumer Defensive', 'equity', 240000000000, 170, 8.2, NULL),
('WMT', 'Walmart Inc.', 'NYSE', 'Consumer Defensive', 'equity', 650000000000, 87, 2.4, NULL),
('HD', 'Home Depot', 'NYSE', 'Consumer Cyclical', 'equity', 370000000000, 380, 15.1, NULL),
('DIS', 'Walt Disney Co.', 'NYSE', 'Communication Services', 'equity', 210000000000, 110, 4.8, NULL),
('NFLX', 'Netflix Inc.', 'NASDAQ', 'Communication Services', 'equity', 550000000000, 990, 19.3, NULL),
('CRM', 'Salesforce', 'NYSE', 'Technology', 'equity', 310000000000, 325, 7.9, NULL),
('ADBE', 'Adobe Inc.', 'NASDAQ', 'Technology', 'equity', 240000000000, 520, 16.1, NULL),
('AMD', 'Advanced Micro Devices', 'NASDAQ', 'Technology', 'equity', 320000000000, 178, 1.6, NULL),
('INTC', 'Intel Corp.', 'NASDAQ', 'Technology', 'equity', 90000000000, 24, 0.9, NULL),
('QCOM', 'Qualcomm Inc.', 'NASDAQ', 'Technology', 'equity', 190000000000, 170, 8.1, NULL),
('TXN', 'Texas Instruments', 'NASDAQ', 'Technology', 'equity', 170000000000, 188, 6.2, NULL),
('AVGO', 'Broadcom Inc.', 'NASDAQ', 'Technology', 'equity', 800000000000, 1400, 12.4, NULL),
('MU', 'Micron Technology', 'NASDAQ', 'Technology', 'equity', 140000000000, 125, 4.8, NULL),
('AMAT', 'Applied Materials', 'NASDAQ', 'Technology', 'equity', 180000000000, 220, 8.8, NULL),
('ASML', 'ASML Holding', 'NASDAQ', 'Technology', 'equity', 350000000000, 950, 24.5, NULL),
-- ETFs
('SPY', 'SPDR S&P 500 ETF', 'ARCA', 'ETF', 'etf', NULL, 581, NULL, NULL),
('QQQ', 'Invesco QQQ Trust', 'NASDAQ', 'ETF', 'etf', NULL, 492, NULL, NULL),
('IWM', 'iShares Russell 2000 ETF', 'ARCA', 'ETF', 'etf', NULL, 249, NULL, NULL),
('DIA', 'SPDR Dow Jones Industrial Average ETF', 'ARCA', 'ETF', 'etf', NULL, 432, NULL, NULL),
('XLK', 'Technology Select Sector SPDR Fund', 'ARCA', 'Technology', 'etf', NULL, 220, NULL, NULL),
('XLV', 'Health Care Select Sector SPDR Fund', 'ARCA', 'Healthcare', 'etf', NULL, 145, NULL, NULL),
('XLF', 'Financial Select Sector SPDR Fund', 'ARCA', 'Financial Services', 'etf', NULL, 44, NULL, NULL),
('XLE', 'Energy Select Sector SPDR Fund', 'ARCA', 'Energy', 'etf', NULL, 88, NULL, NULL),
('XLI', 'Industrial Select Sector SPDR Fund', 'ARCA', 'Industrials', 'etf', NULL, 118, NULL, NULL),
('XLC', 'Communication Services Select SPDR Fund', 'ARCA', 'Communication Services', 'etf', NULL, 85, NULL, NULL),
('XLP', 'Consumer Staples Select Sector SPDR Fund', 'ARCA', 'Consumer Defensive', 'etf', NULL, 80, NULL, NULL),
('XLU', 'Utilities Select Sector SPDR Fund', 'ARCA', 'Utilities', 'etf', NULL, 74, NULL, NULL),
('XLRE', 'Real Estate Select Sector SPDR Fund', 'ARCA', 'Real Estate', 'etf', NULL, 42, NULL, NULL),
('XLB', 'Materials Select Sector SPDR Fund', 'ARCA', 'Basic Materials', 'etf', NULL, 88, NULL, NULL),
('XLY', 'Consumer Discretionary Select Sector SPDR Fund', 'ARCA', 'Consumer Cyclical', 'etf', NULL, 195, NULL, NULL),
-- Indices
('^GSPC', 'S&P 500', 'INDEX', 'Index', 'index', NULL, 5780, NULL, NULL),
('^DJI', 'Dow Jones Industrial Average', 'INDEX', 'Index', 'index', NULL, 43250, NULL, NULL),
('^IXIC', 'NASDAQ Composite', 'INDEX', 'Index', 'index', NULL, 18450, NULL, NULL),
('^RUT', 'Russell 2000', 'INDEX', 'Index', 'index', NULL, 2180, NULL, NULL),
('^VIX', 'CBOE Volatility Index', 'CBOE', 'Volatility', 'index', NULL, 17.5, NULL, NULL),
('^NYA', 'NYSE Composite', 'INDEX', 'Index', 'index', NULL, 19800, NULL, NULL),
('^FTSE', 'FTSE 100', 'INDEX', 'Index', 'index', NULL, 8200, NULL, NULL),
('^GDAXI', 'DAX', 'INDEX', 'Index', 'index', NULL, 18500, NULL, NULL),
('^N225', 'Nikkei 225', 'INDEX', 'Index', 'index', NULL, 39500, NULL, NULL),
-- Commodities
('GC=F', 'Gold Futures', 'COMEX', 'Commodity', 'commodity', NULL, 2985, NULL, NULL),
('CL=F', 'Crude Oil WTI', 'NYMEX', 'Commodity', 'commodity', NULL, 68.4, NULL, NULL),
-- Crypto
('ADA-USD', 'Cardano USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'cardano'),
('AVAX-USD', 'Avalanche USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'avalanche-2'),
('BTC-USD', 'Bitcoin USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'bitcoin'),
('DOGE-USD', 'Dogecoin USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'dogecoin'),
('DOT-USD', 'Polkadot USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'polkadot'),
('ETH-USD', 'Ethereum USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'ethereum'),
('LINK-USD', 'Chainlink USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'chainlink'),
('LTC-USD', 'Litecoin USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'litecoin'),
('MATIC-USD', 'Polygon USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'matic-network'),
('SOL-USD', 'Solana USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'solana'),
('UNI-USD', 'Uniswap USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'uniswap'),
('XRP-USD', 'XRP USD', 'CRYPTO', 'Crypto', 'crypto', NULL, NULL, NULL, 'ripple'),
-- Forex
('AUDUSD', 'Australian Dollar / US Dollar', 'FX', 'Forex', 'forex', NULL, NULL, NULL, NULL),
('EURUSD', 'Euro / US Dollar', 'FX', 'Forex', 'forex', NULL, NULL, NULL, NULL),
('GBPUSD', 'British Pound / US Dollar', 'FX', 'Forex', 'forex', NULL, NULL, NULL, NULL),
('NZDUSD', 'New Zealand Dollar / US Dollar', 'FX', 'Forex', 'forex', NULL, NULL, NULL, NULL),
('USDCAD', 'US Dollar / Canadian Dollar', 'FX', 'Forex', 'forex', NULL, NULL, NULL, NULL),
('USDCHF', 'US Dollar / Swiss Franc', 'FX', 'Forex', 'forex', NULL, NULL, NULL, NULL),
('USDJPY', 'US Dollar / Japanese Yen', 'FX', 'Forex', 'forex', NULL, NULL, NULL, NULL)
ON CONFLICT (symbol) DO NOTHING;
